name: Build e Deploy da aplicação Java para o App Services

on:
#  push:
#    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # 1. Configura o ambiente Java 17 (compatível com a stack Tomcat 17 do Azure)
    - name: Set up Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # 2. Compila a aplicação e gera o arquivo .war usando o Maven
    - name: Build with Maven
      run: mvn clean package -DskipTests

    # 3. Faz o deploy do artefato gerado (.war) para o Azure App Service usando o Publish Profile
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: 'target/*.war'